name: Build image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: "linux-amd64-cpu4"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          endpoint: builders
      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: context
          file: Dockerfile
          target: base
          push: true
          pull: true
          tags: rapidsai/test-ci-permissions:latest
